# Generated by Django 4.1.4 on 2023-01-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_material', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
